# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5edec6853d978280bb92bb02f2d7e341d7bb3df1f93971f170312200da9cd865d19237cc69b3d3bbd7bf2713cdc3a6ea9ab7d00a0c86b1ca086f049b96fd5884

test:
  secret_key_base: fee15c46de29fad343763f9536b3b3c87767041d5603be724386b24fd4f97c5cfe239c94b3b868205c8d6f72ac653406dd223df5e9d47292e58f4b974a4e61cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
